# Generated by Django 3.1.1 on 2020-10-02 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='legal_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True, null=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Homem'), ('F', 'Mulher'), ('O', 'Outros')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
