# Generated by Django 3.1.1 on 2020-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201002_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_user',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_user',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
