# Generated by Django 3.1.1 on 2020-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201003_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(null=True, verbose_name='Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='Sem Telefone', max_length=14, verbose_name='Telefone/Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Sem Atribuição', max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salário'),
        ),
    ]
